import { PrismaClient, Category } from '@prisma/client';

const prisma = new PrismaClient();

const items: Array<{
  strapiId: string; title: string; description: string; source: string;
  publishedAt: Date; imageUrl: string | null; url: string;
  category: Category; regionCode: string | null; locale: string;
}> = [
  // ── technology (20) ──────────────────────────────────────────────────────
  { strapiId:'tech-1', title:'GPT-5 Launches with Multimodal Reasoning', description:'OpenAI releases GPT-5 with advanced multimodal capabilities, setting new benchmarks across coding, math, and vision tasks.', source:'TechCrunch', publishedAt:new Date('2025-03-01'), imageUrl:'https://picsum.photos/seed/tech1/800/450', url:'https://techcrunch.com/gpt5-launch', category:Category.technology, regionCode:null, locale:'en' },
  { strapiId:'tech-2', title:'Apple Vision Pro 2 Announced at WWDC', description:'Apple unveils the second generation of its spatial computing headset with a lighter form factor and 4K micro-OLED displays.', source:'The Verge', publishedAt:new Date('2025-03-03'), imageUrl:'https://picsum.photos/seed/tech2/800/450', url:'https://theverge.com/apple-vision-pro-2', category:Category.technology, regionCode:'US', locale:'en' },
  { strapiId:'tech-3', title:'Quantum Computing Hits 1000-Qubit Milestone', description:'IBM announces a 1000-qubit processor, marking a significant step toward practical quantum advantage in chemistry simulations.', source:'Wired', publishedAt:new Date('2025-03-05'), imageUrl:'https://picsum.photos/seed/tech3/800/450', url:'https://wired.com/ibm-1000-qubit', category:Category.technology, regionCode:null, locale:'en' },
  { strapiId:'tech-4', title:'Rust Overtakes Python in Systems Programming Survey', description:'Stack Overflow\'s annual survey shows Rust has become the most-loved language for the tenth consecutive year, now leading in systems use.', source:'Stack Overflow Blog', publishedAt:new Date('2025-03-07'), imageUrl:'https://picsum.photos/seed/tech4/800/450', url:'https://stackoverflow.blog/rust-survey', category:Category.technology, regionCode:null, locale:'en' },
  { strapiId:'tech-5', title:'EU AI Act Enforcement Begins', description:'The European Union begins enforcing the AI Act, requiring high-risk AI systems to undergo conformity assessments before deployment.', source:'Reuters', publishedAt:new Date('2025-03-09'), imageUrl:'https://picsum.photos/seed/tech5/800/450', url:'https://reuters.com/eu-ai-act', category:Category.technology, regionCode:'GB', locale:'en' },
  { strapiId:'tech-6', title:'Tesla Robotaxi Fleet Expands to 10 Cities', description:'Tesla rolls out its fully autonomous robotaxi service to ten major US cities, with no safety driver required.', source:'Bloomberg', publishedAt:new Date('2025-03-11'), imageUrl:'https://picsum.photos/seed/tech6/800/450', url:'https://bloomberg.com/tesla-robotaxi', category:Category.technology, regionCode:'US', locale:'en' },
  { strapiId:'tech-7', title:'Meta Releases Open-Source LLaMA 4', description:'Meta open-sources LLaMA 4, a 70B parameter model that rivals GPT-4 on most benchmarks while running on consumer hardware.', source:'The Register', publishedAt:new Date('2025-03-13'), imageUrl:'https://picsum.photos/seed/tech7/800/450', url:'https://theregister.com/llama4', category:Category.technology, regionCode:null, locale:'en' },
  { strapiId:'tech-8', title:'SpaceX Starship Completes First Orbital Mission', description:'SpaceX\'s Starship successfully completes its first full orbital mission, splashing down in the Pacific Ocean after 90 minutes.', source:'Ars Technica', publishedAt:new Date('2025-03-15'), imageUrl:'https://picsum.photos/seed/tech8/800/450', url:'https://arstechnica.com/starship-orbital', category:Category.technology, regionCode:'US', locale:'en' },
  { strapiId:'tech-9', title:'Google DeepMind Solves Protein Folding for All Known Proteins', description:'DeepMind announces AlphaFold 3 has predicted structures for every known protein, accelerating drug discovery globally.', source:'Nature', publishedAt:new Date('2025-03-17'), imageUrl:'https://picsum.photos/seed/tech9/800/450', url:'https://nature.com/alphafold3', category:Category.technology, regionCode:null, locale:'en' },
  { strapiId:'tech-10', title:'Microsoft Copilot Integrated into Windows 12', description:'Windows 12 ships with deep Copilot integration, allowing AI-assisted file management, coding, and system configuration.', source:'ZDNet', publishedAt:new Date('2025-03-19'), imageUrl:'https://picsum.photos/seed/tech10/800/450', url:'https://zdnet.com/windows12-copilot', category:Category.technology, regionCode:null, locale:'en' },
  { strapiId:'tech-11', title:'5G Standalone Networks Cover 60% of Global Population', description:'GSMA reports that 5G SA networks now cover over 60% of the world\'s population, enabling ultra-low latency applications.', source:'GSMA', publishedAt:new Date('2025-03-21'), imageUrl:'https://picsum.photos/seed/tech11/800/450', url:'https://gsma.com/5g-coverage-2025', category:Category.technology, regionCode:null, locale:'en' },
  { strapiId:'tech-12', title:'NVIDIA Blackwell GPU Breaks AI Training Records', description:'NVIDIA\'s Blackwell architecture achieves 10x the training throughput of Hopper, slashing LLM training costs dramatically.', source:'AnandTech', publishedAt:new Date('2025-03-23'), imageUrl:'https://picsum.photos/seed/tech12/800/450', url:'https://anandtech.com/blackwell', category:Category.technology, regionCode:null, locale:'en' },
  { strapiId:'tech-13', title:'Cybersecurity Breach Exposes 500M Records at Major Cloud Provider', description:'A misconfigured S3 bucket at a top-three cloud provider exposed half a billion customer records before being patched.', source:'Krebs on Security', publishedAt:new Date('2025-03-25'), imageUrl:'https://picsum.photos/seed/tech13/800/450', url:'https://krebsonsecurity.com/cloud-breach', category:Category.technology, regionCode:null, locale:'en' },
  { strapiId:'tech-14', title:'WebAssembly 3.0 Spec Finalised', description:'The W3C finalises the WebAssembly 3.0 specification, adding garbage collection, threads, and SIMD support to the standard.', source:'MDN Blog', publishedAt:new Date('2025-03-27'), imageUrl:'https://picsum.photos/seed/tech14/800/450', url:'https://developer.mozilla.org/wasm3', category:Category.technology, regionCode:null, locale:'en' },
  { strapiId:'tech-15', title:'Amazon Launches Satellite Internet in 50 New Countries', description:'Amazon\'s Project Kuiper begins service in 50 additional countries, bringing broadband to remote regions across Africa and Asia.', source:'CNBC', publishedAt:new Date('2025-03-29'), imageUrl:'https://picsum.photos/seed/tech15/800/450', url:'https://cnbc.com/kuiper-expansion', category:Category.technology, regionCode:null, locale:'en' },
  { strapiId:'tech-16', title:'Open-Source AI Coding Assistant Tops GitHub Stars', description:'Tabby, an open-source self-hosted coding assistant, surpasses GitHub Copilot in community adoption metrics.', source:'GitHub Blog', publishedAt:new Date('2025-03-31'), imageUrl:'https://picsum.photos/seed/tech16/800/450', url:'https://github.blog/tabby', category:Category.technology, regionCode:null, locale:'en' },
  { strapiId:'tech-17', title:'Foldable Phones Capture 15% of Premium Market', description:'IDC data shows foldable smartphones now account for 15% of the premium segment, led by Samsung and Huawei.', source:'IDC', publishedAt:new Date('2025-04-02'), imageUrl:'https://picsum.photos/seed/tech17/800/450', url:'https://idc.com/foldable-2025', category:Category.technology, regionCode:null, locale:'en' },
  { strapiId:'tech-18', title:'Passkeys Replace Passwords at Major Banks', description:'HSBC, JPMorgan, and Barclays complete their passkey rollouts, eliminating password-based login for 200M customers.', source:'Financial Times', publishedAt:new Date('2025-04-04'), imageUrl:'https://picsum.photos/seed/tech18/800/450', url:'https://ft.com/passkeys-banks', category:Category.technology, regionCode:'GB', locale:'en' },
  { strapiId:'tech-19', title:'Neuralink Receives FDA Approval for Second Trial', description:'Neuralink receives FDA approval for a second human trial of its brain-computer interface, targeting motor neuron disease patients.', source:'MIT Technology Review', publishedAt:new Date('2025-04-06'), imageUrl:'https://picsum.photos/seed/tech19/800/450', url:'https://technologyreview.com/neuralink-fda', category:Category.technology, regionCode:'US', locale:'en' },
  { strapiId:'tech-20', title:'TypeScript 6.0 Ships with Native Decorators', description:'TypeScript 6.0 ships with native decorator support aligned to the TC39 proposal, removing the need for experimentalDecorators.', source:'TypeScript Blog', publishedAt:new Date('2025-04-08'), imageUrl:'https://picsum.photos/seed/tech20/800/450', url:'https://devblogs.microsoft.com/typescript6', category:Category.technology, regionCode:null, locale:'en' },
  // ── sports (20) ──────────────────────────────────────────────────────────
  { strapiId:'sport-1', title:'Champions League Final: Real Madrid vs Manchester City', description:'Real Madrid and Manchester City meet in a historic Champions League final at Wembley, with both clubs chasing a record sixth title.', source:'BBC Sport', publishedAt:new Date('2025-03-02'), imageUrl:'https://picsum.photos/seed/sport1/800/450', url:'https://bbc.com/sport/ucl-final', category:Category.sports, regionCode:'GB', locale:'en' },
  { strapiId:'sport-2', title:'Serena Williams Returns to Grand Slam Tennis', description:'Serena Williams announces a comeback at the French Open, ending a two-year retirement at age 43.', source:'ESPN', publishedAt:new Date('2025-03-04'), imageUrl:'https://picsum.photos/seed/sport2/800/450', url:'https://espn.com/serena-comeback', category:Category.sports, regionCode:'US', locale:'en' },
  { strapiId:'sport-3', title:'NBA All-Star Weekend Breaks Viewership Records', description:'The 2025 NBA All-Star Weekend draws 45 million viewers globally, the highest since 2003, driven by international streaming.', source:'Sports Illustrated', publishedAt:new Date('2025-03-06'), imageUrl:'https://picsum.photos/seed/sport3/800/450', url:'https://si.com/nba-allstar-2025', category:Category.sports, regionCode:'US', locale:'en' },
  { strapiId:'sport-4', title:'Formula 1 Introduces Hydrogen-Powered Cars for 2027', description:'The FIA confirms that Formula 1 will transition to hydrogen fuel cell powertrains from the 2027 season.', source:'Autosport', publishedAt:new Date('2025-03-08'), imageUrl:'https://picsum.photos/seed/sport4/800/450', url:'https://autosport.com/f1-hydrogen-2027', category:Category.sports, regionCode:null, locale:'en' },
  { strapiId:'sport-5', title:'World Cup 2026 Host Cities Confirmed', description:'FIFA confirms the 16 host cities for the 2026 FIFA World Cup across the USA, Canada, and Mexico.', source:'FIFA', publishedAt:new Date('2025-03-10'), imageUrl:'https://picsum.photos/seed/sport5/800/450', url:'https://fifa.com/worldcup2026-cities', category:Category.sports, regionCode:null, locale:'en' },
  { strapiId:'sport-6', title:'Novak Djokovic Wins Record 25th Grand Slam', description:'Djokovic claims his 25th Grand Slam title at the Australian Open, extending his own all-time record.', source:'Tennis.com', publishedAt:new Date('2025-03-12'), imageUrl:'https://picsum.photos/seed/sport6/800/450', url:'https://tennis.com/djokovic-25', category:Category.sports, regionCode:null, locale:'en' },
  { strapiId:'sport-7', title:'Olympics 2028 LA Adds Esports as Medal Event', description:'The IOC confirms that esports will be a full medal event at the 2028 Los Angeles Olympics, featuring six titles.', source:'Olympic Channel', publishedAt:new Date('2025-03-14'), imageUrl:'https://picsum.photos/seed/sport7/800/450', url:'https://olympics.com/esports-2028', category:Category.sports, regionCode:'US', locale:'en' },
  { strapiId:'sport-8', title:'Premier League Clubs Agree to Salary Cap', description:'All 20 Premier League clubs vote to introduce a £200M salary cap from the 2026-27 season to improve financial sustainability.', source:'The Guardian', publishedAt:new Date('2025-03-16'), imageUrl:'https://picsum.photos/seed/sport8/800/450', url:'https://theguardian.com/pl-salary-cap', category:Category.sports, regionCode:'GB', locale:'en' },
  { strapiId:'sport-9', title:'LeBron James Retires After 22 NBA Seasons', description:'LeBron James announces his retirement from the NBA, finishing with 42,000 career points and four championships.', source:'ESPN', publishedAt:new Date('2025-03-18'), imageUrl:'https://picsum.photos/seed/sport9/800/450', url:'https://espn.com/lebron-retires', category:Category.sports, regionCode:'US', locale:'en' },
  { strapiId:'sport-10', title:'Tour de France Route 2025 Unveiled', description:'The 2025 Tour de France route features a record six mountain finishes and a new stage through the Pyrenees.', source:'Cycling Weekly', publishedAt:new Date('2025-03-20'), imageUrl:'https://picsum.photos/seed/sport10/800/450', url:'https://cyclingweekly.com/tdf2025-route', category:Category.sports, regionCode:'FR', locale:'en' },
  { strapiId:'sport-11', title:'India Wins Cricket World Cup for Fourth Time', description:'India defeats Australia in the final of the ICC Cricket World Cup, claiming their fourth title in front of 100,000 fans in Mumbai.', source:'Cricinfo', publishedAt:new Date('2025-03-22'), imageUrl:'https://picsum.photos/seed/sport11/800/450', url:'https://cricinfo.com/cwc2025-final', category:Category.sports, regionCode:'IN', locale:'en' },
  { strapiId:'sport-12', title:'NFL Expands to 18-Game Regular Season', description:'The NFL and NFLPA agree to expand the regular season to 18 games starting in 2026, with an additional bye week.', source:'NFL.com', publishedAt:new Date('2025-03-24'), imageUrl:'https://picsum.photos/seed/sport12/800/450', url:'https://nfl.com/18-game-season', category:Category.sports, regionCode:'US', locale:'en' },
  { strapiId:'sport-13', title:'Simone Biles Wins Fifth Olympic Gold', description:'Simone Biles claims her fifth Olympic gold medal at the Paris 2024 Games, cementing her status as the greatest gymnast of all time.', source:'NBC Sports', publishedAt:new Date('2025-03-26'), imageUrl:'https://picsum.photos/seed/sport13/800/450', url:'https://nbcsports.com/biles-gold', category:Category.sports, regionCode:'US', locale:'en' },
  { strapiId:'sport-14', title:'Manchester United Appoints New Manager', description:'Manchester United appoints Xabi Alonso as their new manager on a three-year contract following a disappointing season.', source:'Sky Sports', publishedAt:new Date('2025-03-28'), imageUrl:'https://picsum.photos/seed/sport14/800/450', url:'https://skysports.com/mufc-alonso', category:Category.sports, regionCode:'GB', locale:'en' },
  { strapiId:'sport-15', title:'UFC 300 Breaks Pay-Per-View Records', description:'UFC 300 becomes the highest-grossing pay-per-view event in combat sports history, with 3.5 million buys worldwide.', source:'MMA Fighting', publishedAt:new Date('2025-03-30'), imageUrl:'https://picsum.photos/seed/sport15/800/450', url:'https://mmafighting.com/ufc300-record', category:Category.sports, regionCode:'US', locale:'en' },
  { strapiId:'sport-16', title:'Wimbledon Introduces Tiebreak in Final Set', description:'Wimbledon announces it will adopt a final-set tiebreak at 6-6 from 2025, ending the tradition of indefinite final sets.', source:'BBC Sport', publishedAt:new Date('2025-04-01'), imageUrl:'https://picsum.photos/seed/sport16/800/450', url:'https://bbc.com/sport/wimbledon-tiebreak', category:Category.sports, regionCode:'GB', locale:'en' },
  { strapiId:'sport-17', title:'Golden State Warriors Win NBA Championship', description:'The Golden State Warriors defeat the Boston Celtics in seven games to claim their sixth NBA championship.', source:'ESPN', publishedAt:new Date('2025-04-03'), imageUrl:'https://picsum.photos/seed/sport17/800/450', url:'https://espn.com/nba-finals-2025', category:Category.sports, regionCode:'US', locale:'en' },
  { strapiId:'sport-18', title:'Paris Saint-Germain Wins Ligue 1 for 12th Consecutive Year', description:'PSG clinch their 12th consecutive Ligue 1 title with five games to spare, setting a new European record.', source:'L\'Équipe', publishedAt:new Date('2025-04-05'), imageUrl:'https://picsum.photos/seed/sport18/800/450', url:'https://lequipe.fr/psg-ligue1-2025', category:Category.sports, regionCode:'FR', locale:'en' },
  { strapiId:'sport-19', title:'Usain Bolt\'s 100m World Record Finally Broken', description:'Noah Lyles runs 9.57 seconds at the World Athletics Championships, breaking Usain Bolt\'s 16-year-old world record.', source:'World Athletics', publishedAt:new Date('2025-04-07'), imageUrl:'https://picsum.photos/seed/sport19/800/450', url:'https://worldathletics.org/lyles-wr', category:Category.sports, regionCode:null, locale:'en' },
  { strapiId:'sport-20', title:'Rugby World Cup 2027 Awarded to Australia', description:'World Rugby awards the 2027 Rugby World Cup to Australia, marking the country\'s second hosting of the tournament.', source:'Rugby World', publishedAt:new Date('2025-04-09'), imageUrl:'https://picsum.photos/seed/sport20/800/450', url:'https://rugbyworld.com/rwc2027-australia', category:Category.sports, regionCode:'AU', locale:'en' },
  // ── finance (20) ─────────────────────────────────────────────────────────
  { strapiId:'fin-1', title:'Bitcoin Hits $150,000 All-Time High', description:'Bitcoin surpasses $150,000 for the first time, driven by institutional ETF inflows and reduced supply post-halving.', source:'CoinDesk', publishedAt:new Date('2025-03-01'), imageUrl:'https://picsum.photos/seed/fin1/800/450', url:'https://coindesk.com/btc-150k', category:Category.finance, regionCode:null, locale:'en' },
  { strapiId:'fin-2', title:'Federal Reserve Cuts Rates to 3.5%', description:'The Fed cuts the federal funds rate by 25 basis points to 3.5%, citing cooling inflation and slowing job growth.', source:'Wall Street Journal', publishedAt:new Date('2025-03-03'), imageUrl:'https://picsum.photos/seed/fin2/800/450', url:'https://wsj.com/fed-rate-cut-2025', category:Category.finance, regionCode:'US', locale:'en' },
  { strapiId:'fin-3', title:'S&P 500 Crosses 7,000 Points', description:'The S&P 500 index closes above 7,000 for the first time, fuelled by strong earnings from the technology sector.', source:'Bloomberg', publishedAt:new Date('2025-03-05'), imageUrl:'https://picsum.photos/seed/fin3/800/450', url:'https://bloomberg.com/sp500-7000', category:Category.finance, regionCode:'US', locale:'en' },
  { strapiId:'fin-4', title:'Apple Becomes First $4 Trillion Company', description:'Apple\'s market capitalisation crosses $4 trillion, making it the first company in history to reach that milestone.', source:'Reuters', publishedAt:new Date('2025-03-07'), imageUrl:'https://picsum.photos/seed/fin4/800/450', url:'https://reuters.com/apple-4-trillion', category:Category.finance, regionCode:'US', locale:'en' },
  { strapiId:'fin-5', title:'EU Launches Digital Euro Pilot', description:'The European Central Bank launches a pilot of the digital euro with 10,000 participants across five member states.', source:'Financial Times', publishedAt:new Date('2025-03-09'), imageUrl:'https://picsum.photos/seed/fin5/800/450', url:'https://ft.com/digital-euro-pilot', category:Category.finance, regionCode:'DE', locale:'en' },
  { strapiId:'fin-6', title:'Goldman Sachs Predicts Recession Risk at 35%', description:'Goldman Sachs raises its US recession probability to 35% for 2025, citing trade policy uncertainty and tightening credit.', source:'Goldman Sachs Research', publishedAt:new Date('2025-03-11'), imageUrl:'https://picsum.photos/seed/fin6/800/450', url:'https://goldmansachs.com/recession-2025', category:Category.finance, regionCode:'US', locale:'en' },
  { strapiId:'fin-7', title:'Stripe Valued at $95 Billion in Secondary Market', description:'Stripe shares trade at a $95 billion valuation in secondary markets ahead of a rumoured 2025 IPO.', source:'TechCrunch', publishedAt:new Date('2025-03-13'), imageUrl:'https://picsum.photos/seed/fin7/800/450', url:'https://techcrunch.com/stripe-valuation', category:Category.finance, regionCode:'US', locale:'en' },
  { strapiId:'fin-8', title:'China Cuts Reserve Requirement Ratio to Boost Economy', description:'The People\'s Bank of China cuts the reserve requirement ratio by 50 basis points to inject $140 billion into the economy.', source:'South China Morning Post', publishedAt:new Date('2025-03-15'), imageUrl:'https://picsum.photos/seed/fin8/800/450', url:'https://scmp.com/pboc-rrr-cut', category:Category.finance, regionCode:'CN', locale:'en' },
  { strapiId:'fin-9', title:'Warren Buffett Steps Down as Berkshire CEO', description:'Warren Buffett announces his retirement as CEO of Berkshire Hathaway at age 94, naming Greg Abel as his successor.', source:'CNBC', publishedAt:new Date('2025-03-17'), imageUrl:'https://picsum.photos/seed/fin9/800/450', url:'https://cnbc.com/buffett-retires', category:Category.finance, regionCode:'US', locale:'en' },
  { strapiId:'fin-10', title:'UK Inflation Falls to 2% Target', description:'UK CPI inflation falls to the Bank of England\'s 2% target for the first time since 2021, raising hopes for rate cuts.', source:'BBC News', publishedAt:new Date('2025-03-19'), imageUrl:'https://picsum.photos/seed/fin10/800/450', url:'https://bbc.com/uk-inflation-2025', category:Category.finance, regionCode:'GB', locale:'en' },
  { strapiId:'fin-11', title:'Ethereum ETF Approved by SEC', description:'The SEC approves spot Ethereum ETFs, opening the door for institutional investment in the second-largest cryptocurrency.', source:'CoinTelegraph', publishedAt:new Date('2025-03-21'), imageUrl:'https://picsum.photos/seed/fin11/800/450', url:'https://cointelegraph.com/eth-etf-sec', category:Category.finance, regionCode:'US', locale:'en' },
  { strapiId:'fin-12', title:'Global Debt Reaches $320 Trillion', description:'The Institute of International Finance reports global debt has reached a record $320 trillion, equal to 330% of world GDP.', source:'IIF', publishedAt:new Date('2025-03-23'), imageUrl:'https://picsum.photos/seed/fin12/800/450', url:'https://iif.com/global-debt-2025', category:Category.finance, regionCode:null, locale:'en' },
  { strapiId:'fin-13', title:'Visa and Mastercard Settle Merchant Fee Lawsuit for $30B', description:'Visa and Mastercard agree to a $30 billion settlement with US merchants over swipe fee antitrust claims.', source:'Reuters', publishedAt:new Date('2025-03-25'), imageUrl:'https://picsum.photos/seed/fin13/800/450', url:'https://reuters.com/visa-mastercard-settlement', category:Category.finance, regionCode:'US', locale:'en' },
  { strapiId:'fin-14', title:'Japan Ends Negative Interest Rate Policy', description:'The Bank of Japan raises its benchmark rate to 0.5%, ending decades of negative interest rate policy.', source:'Nikkei Asia', publishedAt:new Date('2025-03-27'), imageUrl:'https://picsum.photos/seed/fin14/800/450', url:'https://asia.nikkei.com/boj-rate-hike', category:Category.finance, regionCode:'JP', locale:'en' },
  { strapiId:'fin-15', title:'OpenAI Raises $10 Billion at $300 Billion Valuation', description:'OpenAI closes a $10 billion funding round led by SoftBank, valuing the company at $300 billion.', source:'The Information', publishedAt:new Date('2025-03-29'), imageUrl:'https://picsum.photos/seed/fin15/800/450', url:'https://theinformation.com/openai-funding', category:Category.finance, regionCode:'US', locale:'en' },
  { strapiId:'fin-16', title:'India Surpasses Japan as Third Largest Economy', description:'IMF data confirms India has overtaken Japan to become the world\'s third largest economy by nominal GDP.', source:'IMF', publishedAt:new Date('2025-03-31'), imageUrl:'https://picsum.photos/seed/fin16/800/450', url:'https://imf.org/india-gdp-2025', category:Category.finance, regionCode:'IN', locale:'en' },
  { strapiId:'fin-17', title:'BNPL Regulations Take Effect in the UK', description:'New FCA rules require buy-now-pay-later providers to conduct affordability checks, affecting Klarna and Afterpay.', source:'Financial Times', publishedAt:new Date('2025-04-02'), imageUrl:'https://picsum.photos/seed/fin17/800/450', url:'https://ft.com/bnpl-fca-rules', category:Category.finance, regionCode:'GB', locale:'en' },
  { strapiId:'fin-18', title:'Gold Hits $3,000 Per Ounce', description:'Gold prices reach $3,000 per troy ounce for the first time, driven by central bank buying and geopolitical uncertainty.', source:'Kitco', publishedAt:new Date('2025-04-04'), imageUrl:'https://picsum.photos/seed/fin18/800/450', url:'https://kitco.com/gold-3000', category:Category.finance, regionCode:null, locale:'en' },
  { strapiId:'fin-19', title:'Robinhood Launches Retirement Accounts in Europe', description:'Robinhood expands its retirement account offering to the UK and Germany, targeting millennial investors.', source:'TechCrunch', publishedAt:new Date('2025-04-06'), imageUrl:'https://picsum.photos/seed/fin19/800/450', url:'https://techcrunch.com/robinhood-europe-ira', category:Category.finance, regionCode:'GB', locale:'en' },
  { strapiId:'fin-20', title:'Carbon Credit Market Reaches $100 Billion', description:'The voluntary carbon credit market surpasses $100 billion in annual trading volume, driven by corporate net-zero commitments.', source:'Bloomberg Green', publishedAt:new Date('2025-04-08'), imageUrl:'https://picsum.photos/seed/fin20/800/450', url:'https://bloomberg.com/carbon-credits-100b', category:Category.finance, regionCode:null, locale:'en' },
  // ── entertainment (20) ───────────────────────────────────────────────────
  { strapiId:'ent-1', title:'Avatar 3 Breaks Opening Weekend Record', description:'James Cameron\'s Avatar 3 earns $450 million in its opening weekend, surpassing Avengers: Endgame\'s record.', source:'Variety', publishedAt:new Date('2025-03-02'), imageUrl:'https://picsum.photos/seed/ent1/800/450', url:'https://variety.com/avatar3-record', category:Category.entertainment, regionCode:null, locale:'en' },
  { strapiId:'ent-2', title:'Netflix Reaches 350 Million Subscribers', description:'Netflix reports 350 million paid subscribers globally, driven by its ad-supported tier and live sports content.', source:'The Hollywood Reporter', publishedAt:new Date('2025-03-04'), imageUrl:'https://picsum.photos/seed/ent2/800/450', url:'https://hollywoodreporter.com/netflix-350m', category:Category.entertainment, regionCode:null, locale:'en' },
  { strapiId:'ent-3', title:'Taylor Swift Eras Tour Becomes Highest-Grossing Concert Ever', description:'Taylor Swift\'s Eras Tour surpasses $2 billion in gross revenue, becoming the highest-grossing concert tour in history.', source:'Billboard', publishedAt:new Date('2025-03-06'), imageUrl:'https://picsum.photos/seed/ent3/800/450', url:'https://billboard.com/eras-tour-record', category:Category.entertainment, regionCode:'US', locale:'en' },
  { strapiId:'ent-4', title:'GTA VI Launches to 20 Million Day-One Sales', description:'Rockstar Games\' Grand Theft Auto VI sells 20 million copies on its first day, the biggest entertainment launch in history.', source:'IGN', publishedAt:new Date('2025-03-08'), imageUrl:'https://picsum.photos/seed/ent4/800/450', url:'https://ign.com/gta6-launch', category:Category.entertainment, regionCode:null, locale:'en' },
  { strapiId:'ent-5', title:'Oscars 2025: Oppenheimer Sequel Wins Best Picture', description:'The Oscars ceremony sees the Oppenheimer sequel take Best Picture, with Cillian Murphy winning Best Actor for the second time.', source:'The Guardian', publishedAt:new Date('2025-03-10'), imageUrl:'https://picsum.photos/seed/ent5/800/450', url:'https://theguardian.com/oscars-2025', category:Category.entertainment, regionCode:'US', locale:'en' },
  { strapiId:'ent-6', title:'Spotify Launches AI-Generated Personalised Podcasts', description:'Spotify introduces AI-generated daily podcasts tailored to each user\'s listening history and interests.', source:'TechCrunch', publishedAt:new Date('2025-03-12'), imageUrl:'https://picsum.photos/seed/ent6/800/450', url:'https://techcrunch.com/spotify-ai-podcasts', category:Category.entertainment, regionCode:null, locale:'en' },
  { strapiId:'ent-7', title:'Disney+ and Hulu Merge into Single Platform', description:'Disney announces the full merger of Disney+ and Hulu into a single streaming platform with 200 million subscribers.', source:'Deadline', publishedAt:new Date('2025-03-14'), imageUrl:'https://picsum.photos/seed/ent7/800/450', url:'https://deadline.com/disney-hulu-merge', category:Category.entertainment, regionCode:'US', locale:'en' },
  { strapiId:'ent-8', title:'K-Pop Group BTS Reunites After Military Service', description:'All seven BTS members complete their mandatory military service and announce a world reunion tour for 2025.', source:'Rolling Stone', publishedAt:new Date('2025-03-16'), imageUrl:'https://picsum.photos/seed/ent8/800/450', url:'https://rollingstone.com/bts-reunion', category:Category.entertainment, regionCode:'KR', locale:'en' },
  { strapiId:'ent-9', title:'The Last of Us Season 3 Renewed by HBO', description:'HBO renews The Last of Us for a third season following record-breaking viewership for the Season 2 finale.', source:'Variety', publishedAt:new Date('2025-03-18'), imageUrl:'https://picsum.photos/seed/ent9/800/450', url:'https://variety.com/tlou-season3', category:Category.entertainment, regionCode:'US', locale:'en' },
  { strapiId:'ent-10', title:'AI-Generated Film Wins Sundance Grand Jury Prize', description:'A feature film created entirely with generative AI tools wins the Sundance Film Festival Grand Jury Prize, sparking industry debate.', source:'IndieWire', publishedAt:new Date('2025-03-20'), imageUrl:'https://picsum.photos/seed/ent10/800/450', url:'https://indiewire.com/ai-film-sundance', category:Category.entertainment, regionCode:'US', locale:'en' },
  { strapiId:'ent-11', title:'Beyoncé\'s Renaissance Film Tops Streaming Charts', description:'Beyoncé\'s Renaissance concert film becomes the most-streamed music documentary of all time within 48 hours of release.', source:'Billboard', publishedAt:new Date('2025-03-22'), imageUrl:'https://picsum.photos/seed/ent11/800/450', url:'https://billboard.com/beyonce-renaissance-film', category:Category.entertainment, regionCode:'US', locale:'en' },
  { strapiId:'ent-12', title:'Nintendo Switch 2 Sells 5 Million Units in First Week', description:'Nintendo\'s Switch 2 console sells 5 million units in its first week, outpacing the original Switch launch.', source:'Eurogamer', publishedAt:new Date('2025-03-24'), imageUrl:'https://picsum.photos/seed/ent12/800/450', url:'https://eurogamer.net/switch2-sales', category:Category.entertainment, regionCode:null, locale:'en' },
  { strapiId:'ent-13', title:'Stranger Things Final Season Breaks Netflix Records', description:'The final season of Stranger Things becomes Netflix\'s most-watched series ever, with 200 million views in its first week.', source:'Deadline', publishedAt:new Date('2025-03-26'), imageUrl:'https://picsum.photos/seed/ent13/800/450', url:'https://deadline.com/stranger-things-final', category:Category.entertainment, regionCode:'US', locale:'en' },
  { strapiId:'ent-14', title:'Cannes 2025 Palme d\'Or Goes to South Korean Director', description:'A South Korean director wins the Palme d\'Or at Cannes 2025 for a film exploring AI consciousness and human identity.', source:'Screen Daily', publishedAt:new Date('2025-03-28'), imageUrl:'https://picsum.photos/seed/ent14/800/450', url:'https://screendaily.com/cannes2025-palme', category:Category.entertainment, regionCode:'FR', locale:'en' },
  { strapiId:'ent-15', title:'Minecraft Movie Earns $1 Billion Worldwide', description:'The Minecraft movie adaptation crosses $1 billion at the global box office, becoming the highest-grossing video game film.', source:'Box Office Mojo', publishedAt:new Date('2025-03-30'), imageUrl:'https://picsum.photos/seed/ent15/800/450', url:'https://boxofficemojo.com/minecraft-movie', category:Category.entertainment, regionCode:null, locale:'en' },
  { strapiId:'ent-16', title:'Grammy Awards Introduce AI Music Category', description:'The Recording Academy introduces a new Grammy category for AI-assisted music production, effective from the 2026 awards.', source:'Rolling Stone', publishedAt:new Date('2025-04-01'), imageUrl:'https://picsum.photos/seed/ent16/800/450', url:'https://rollingstone.com/grammy-ai-category', category:Category.entertainment, regionCode:'US', locale:'en' },
  { strapiId:'ent-17', title:'Dune Part Three Greenlit by Warner Bros', description:'Warner Bros. greenlights Dune Part Three following the critical and commercial success of Dune: Messiah.', source:'Variety', publishedAt:new Date('2025-04-03'), imageUrl:'https://picsum.photos/seed/ent17/800/450', url:'https://variety.com/dune-part-three', category:Category.entertainment, regionCode:'US', locale:'en' },
  { strapiId:'ent-18', title:'TikTok Launches Long-Form Video Platform', description:'TikTok introduces a long-form video platform supporting videos up to 60 minutes, directly competing with YouTube.', source:'The Verge', publishedAt:new Date('2025-04-05'), imageUrl:'https://picsum.photos/seed/ent18/800/450', url:'https://theverge.com/tiktok-longform', category:Category.entertainment, regionCode:null, locale:'en' },
  { strapiId:'ent-19', title:'Eminem Announces Retirement Tour', description:'Eminem announces a farewell world tour spanning 50 cities, marking the end of his 30-year recording career.', source:'NME', publishedAt:new Date('2025-04-07'), imageUrl:'https://picsum.photos/seed/ent19/800/450', url:'https://nme.com/eminem-retirement-tour', category:Category.entertainment, regionCode:'US', locale:'en' },
  { strapiId:'ent-20', title:'Virtual Reality Concert Platform Reaches 10 Million Users', description:'Wave, the VR concert platform, reaches 10 million monthly active users after hosting a record-breaking Ariana Grande show.', source:'TechCrunch', publishedAt:new Date('2025-04-09'), imageUrl:'https://picsum.photos/seed/ent20/800/450', url:'https://techcrunch.com/wave-vr-10m', category:Category.entertainment, regionCode:null, locale:'en' },
  // ── health (20) ──────────────────────────────────────────────────────────
  { strapiId:'hlth-1', title:'Ozempic Approved for Heart Disease Prevention', description:'The FDA approves semaglutide (Ozempic) for cardiovascular disease prevention in non-diabetic patients with obesity.', source:'NEJM', publishedAt:new Date('2025-03-01'), imageUrl:'https://picsum.photos/seed/hlth1/800/450', url:'https://nejm.org/ozempic-heart', category:Category.health, regionCode:'US', locale:'en' },
  { strapiId:'hlth-2', title:'WHO Declares End of COVID-19 Public Health Emergency', description:'The World Health Organization officially declares the end of COVID-19 as a public health emergency of international concern.', source:'WHO', publishedAt:new Date('2025-03-03'), imageUrl:'https://picsum.photos/seed/hlth2/800/450', url:'https://who.int/covid-end-2025', category:Category.health, regionCode:null, locale:'en' },
  { strapiId:'hlth-3', title:'CRISPR Gene Therapy Cures Sickle Cell Disease in Trial', description:'A Phase 3 trial of CRISPR-based gene therapy shows 95% of sickle cell disease patients are symptom-free after two years.', source:'The Lancet', publishedAt:new Date('2025-03-05'), imageUrl:'https://picsum.photos/seed/hlth3/800/450', url:'https://thelancet.com/crispr-sickle-cell', category:Category.health, regionCode:null, locale:'en' },
  { strapiId:'hlth-4', title:'AI Detects Pancreatic Cancer 3 Years Early in Study', description:'A deep learning model trained on routine blood tests detects pancreatic cancer up to three years before clinical diagnosis.', source:'Nature Medicine', publishedAt:new Date('2025-03-07'), imageUrl:'https://picsum.photos/seed/hlth4/800/450', url:'https://nature.com/ai-pancreatic-cancer', category:Category.health, regionCode:null, locale:'en' },
  { strapiId:'hlth-5', title:'UK NHS Launches Universal Mental Health App', description:'The NHS rolls out a free AI-powered mental health app to all UK residents, offering CBT and crisis support 24/7.', source:'BBC Health', publishedAt:new Date('2025-03-09'), imageUrl:'https://picsum.photos/seed/hlth5/800/450', url:'https://bbc.com/health/nhs-mental-health-app', category:Category.health, regionCode:'GB', locale:'en' },
  { strapiId:'hlth-6', title:'Alzheimer\'s Drug Lecanemab Slows Decline by 35%', description:'Long-term data from the CLARITY AD trial shows lecanemab slows cognitive decline by 35% over three years.', source:'JAMA', publishedAt:new Date('2025-03-11'), imageUrl:'https://picsum.photos/seed/hlth6/800/450', url:'https://jamanetwork.com/lecanemab-3yr', category:Category.health, regionCode:null, locale:'en' },
  { strapiId:'hlth-7', title:'Wearable Continuous Glucose Monitor Approved for Non-Diabetics', description:'The FDA clears the first continuous glucose monitor for use by non-diabetic individuals for metabolic health tracking.', source:'MedPage Today', publishedAt:new Date('2025-03-13'), imageUrl:'https://picsum.photos/seed/hlth7/800/450', url:'https://medpagetoday.com/cgm-non-diabetic', category:Category.health, regionCode:'US', locale:'en' },
  { strapiId:'hlth-8', title:'Global Life Expectancy Reaches 75 Years', description:'WHO data shows global average life expectancy has reached 75 years, recovering fully from the COVID-19 setback.', source:'WHO', publishedAt:new Date('2025-03-15'), imageUrl:'https://picsum.photos/seed/hlth8/800/450', url:'https://who.int/life-expectancy-2025', category:Category.health, regionCode:null, locale:'en' },
  { strapiId:'hlth-9', title:'mRNA Flu Vaccine Shows 90% Efficacy in Trial', description:'Moderna\'s mRNA-based influenza vaccine demonstrates 90% efficacy in a Phase 3 trial, far exceeding traditional vaccines.', source:'NEJM', publishedAt:new Date('2025-03-17'), imageUrl:'https://picsum.photos/seed/hlth9/800/450', url:'https://nejm.org/mrna-flu-vaccine', category:Category.health, regionCode:null, locale:'en' },
  { strapiId:'hlth-10', title:'Childhood Obesity Rates Fall for First Time in 20 Years', description:'CDC data shows US childhood obesity rates have declined for the first time in two decades, attributed to GLP-1 medications.', source:'CDC', publishedAt:new Date('2025-03-19'), imageUrl:'https://picsum.photos/seed/hlth10/800/450', url:'https://cdc.gov/obesity-decline-2025', category:Category.health, regionCode:'US', locale:'en' },
  { strapiId:'hlth-11', title:'Lab-Grown Kidney Successfully Transplanted in Human', description:'Surgeons at NYU Langone successfully transplant a lab-grown kidney into a human patient, who remains healthy after six months.', source:'Science', publishedAt:new Date('2025-03-21'), imageUrl:'https://picsum.photos/seed/hlth11/800/450', url:'https://science.org/lab-kidney-transplant', category:Category.health, regionCode:'US', locale:'en' },
  { strapiId:'hlth-12', title:'WHO Approves First Malaria Vaccine for Children', description:'The WHO recommends the R21/Matrix-M malaria vaccine for children under five, with 77% efficacy in trials.', source:'WHO', publishedAt:new Date('2025-03-23'), imageUrl:'https://picsum.photos/seed/hlth12/800/450', url:'https://who.int/malaria-vaccine-r21', category:Category.health, regionCode:null, locale:'en' },
  { strapiId:'hlth-13', title:'Longevity Drug Rapamycin Enters Phase 3 Human Trial', description:'A Phase 3 trial of rapamycin as an anti-aging intervention begins, enrolling 3,000 healthy adults aged 50-70.', source:'Nature Aging', publishedAt:new Date('2025-03-25'), imageUrl:'https://picsum.photos/seed/hlth13/800/450', url:'https://nature.com/rapamycin-trial', category:Category.health, regionCode:'US', locale:'en' },
  { strapiId:'hlth-14', title:'Microplastics Found in Human Brain Tissue', description:'A landmark study finds microplastic particles in human brain tissue samples, raising concerns about neurological effects.', source:'Nature Neuroscience', publishedAt:new Date('2025-03-27'), imageUrl:'https://picsum.photos/seed/hlth14/800/450', url:'https://nature.com/microplastics-brain', category:Category.health, regionCode:null, locale:'en' },
  { strapiId:'hlth-15', title:'Universal Cancer Vaccine Enters Clinical Trials', description:'BioNTech begins Phase 1 trials of a personalised mRNA cancer vaccine targeting 20 different tumour types.', source:'The Lancet Oncology', publishedAt:new Date('2025-03-29'), imageUrl:'https://picsum.photos/seed/hlth15/800/450', url:'https://thelancet.com/biontech-cancer-vaccine', category:Category.health, regionCode:null, locale:'en' },
  { strapiId:'hlth-16', title:'Sleep Tracking Wearables Linked to Better Health Outcomes', description:'A Stanford study of 50,000 wearable users finds consistent sleep tracking correlates with 20% lower cardiovascular risk.', source:'Stanford Medicine', publishedAt:new Date('2025-03-31'), imageUrl:'https://picsum.photos/seed/hlth16/800/450', url:'https://med.stanford.edu/sleep-wearables', category:Category.health, regionCode:'US', locale:'en' },
  { strapiId:'hlth-17', title:'Antibiotic-Resistant Infections Kill 5 Million Annually', description:'A new Lancet study estimates antimicrobial resistance now kills 5 million people per year, calling for urgent global action.', source:'The Lancet', publishedAt:new Date('2025-04-02'), imageUrl:'https://picsum.photos/seed/hlth17/800/450', url:'https://thelancet.com/amr-deaths-2025', category:Category.health, regionCode:null, locale:'en' },
  { strapiId:'hlth-18', title:'Psychedelic Therapy Approved for PTSD in Australia', description:'Australia becomes the first country to approve MDMA-assisted therapy for PTSD, with psilocybin approved for depression.', source:'The BMJ', publishedAt:new Date('2025-04-04'), imageUrl:'https://picsum.photos/seed/hlth18/800/450', url:'https://bmj.com/australia-psychedelic-therapy', category:Category.health, regionCode:'AU', locale:'en' },
  { strapiId:'hlth-19', title:'Gut Microbiome Test Predicts Type 2 Diabetes Risk', description:'A new gut microbiome analysis can predict an individual\'s risk of developing type 2 diabetes with 85% accuracy.', source:'Cell', publishedAt:new Date('2025-04-06'), imageUrl:'https://picsum.photos/seed/hlth19/800/450', url:'https://cell.com/microbiome-diabetes', category:Category.health, regionCode:null, locale:'en' },
  { strapiId:'hlth-20', title:'WHO Sets New Air Quality Guidelines', description:'The WHO tightens its air quality guidelines, reducing the recommended annual PM2.5 limit from 10 to 5 μg/m³.', source:'WHO', publishedAt:new Date('2025-04-08'), imageUrl:'https://picsum.photos/seed/hlth20/800/450', url:'https://who.int/air-quality-2025', category:Category.health, regionCode:null, locale:'en' },
  // ── science (20) ─────────────────────────────────────────────────────────
  { strapiId:'sci-1', title:'James Webb Telescope Discovers Oldest Galaxy', description:'JWST observes a galaxy formed just 290 million years after the Big Bang, the oldest ever detected.', source:'NASA', publishedAt:new Date('2025-03-01'), imageUrl:'https://picsum.photos/seed/sci1/800/450', url:'https://nasa.gov/jwst-oldest-galaxy', category:Category.science, regionCode:null, locale:'en' },
  { strapiId:'sci-2', title:'Nuclear Fusion Reactor Achieves Net Energy Gain for 10 Seconds', description:'The National Ignition Facility sustains net energy gain from nuclear fusion for 10 seconds, a major step toward commercial fusion.', source:'Science', publishedAt:new Date('2025-03-03'), imageUrl:'https://picsum.photos/seed/sci2/800/450', url:'https://science.org/nif-fusion-10s', category:Category.science, regionCode:'US', locale:'en' },
  { strapiId:'sci-3', title:'Scientists Revive 46,000-Year-Old Worm from Siberian Permafrost', description:'Russian scientists successfully revive a nematode worm frozen in Siberian permafrost for 46,000 years.', source:'Nature', publishedAt:new Date('2025-03-05'), imageUrl:'https://picsum.photos/seed/sci3/800/450', url:'https://nature.com/permafrost-worm', category:Category.science, regionCode:'RU', locale:'en' },
  { strapiId:'sci-4', title:'Room-Temperature Superconductor Confirmed by Independent Labs', description:'Three independent laboratories confirm a room-temperature superconductor material, potentially revolutionising energy transmission.', source:'Physical Review Letters', publishedAt:new Date('2025-03-07'), imageUrl:'https://picsum.photos/seed/sci4/800/450', url:'https://journals.aps.org/room-temp-superconductor', category:Category.science, regionCode:null, locale:'en' },
  { strapiId:'sci-5', title:'Mars Sample Return Mission Launches', description:'NASA and ESA jointly launch the Mars Sample Return mission to retrieve rock samples collected by the Perseverance rover.', source:'NASA', publishedAt:new Date('2025-03-09'), imageUrl:'https://picsum.photos/seed/sci5/800/450', url:'https://nasa.gov/mars-sample-return', category:Category.science, regionCode:'US', locale:'en' },
  { strapiId:'sci-6', title:'New Species of Whale Discovered in Pacific', description:'Marine biologists discover a previously unknown species of beaked whale in the deep Pacific Ocean.', source:'PLOS ONE', publishedAt:new Date('2025-03-11'), imageUrl:'https://picsum.photos/seed/sci6/800/450', url:'https://journals.plos.org/new-whale-species', category:Category.science, regionCode:null, locale:'en' },
  { strapiId:'sci-7', title:'Gravitational Wave Detector Spots Neutron Star Merger', description:'LIGO detects gravitational waves from a neutron star merger 500 million light-years away, enabling multi-messenger astronomy.', source:'Astrophysical Journal', publishedAt:new Date('2025-03-13'), imageUrl:'https://picsum.photos/seed/sci7/800/450', url:'https://iopscience.iop.org/ligo-neutron-star', category:Category.science, regionCode:'US', locale:'en' },
  { strapiId:'sci-8', title:'Plastic-Eating Enzyme Breaks Down PET in 24 Hours', description:'Scientists engineer a super-enzyme that degrades PET plastic in 24 hours at room temperature, offering a recycling breakthrough.', source:'Nature Catalysis', publishedAt:new Date('2025-03-15'), imageUrl:'https://picsum.photos/seed/sci8/800/450', url:'https://nature.com/plastic-enzyme-2025', category:Category.science, regionCode:'GB', locale:'en' },
  { strapiId:'sci-9', title:'First Complete Human Genome Sequenced for Under $100', description:'A new nanopore sequencing technique produces a complete human genome sequence for under $100, democratising genomics.', source:'Genome Research', publishedAt:new Date('2025-03-17'), imageUrl:'https://picsum.photos/seed/sci9/800/450', url:'https://genome.cshlp.org/100-dollar-genome', category:Category.science, regionCode:null, locale:'en' },
  { strapiId:'sci-10', title:'Voyager 1 Sends New Data from Interstellar Space', description:'NASA\'s Voyager 1 resumes full science operations after a software fix, transmitting new data from 24 billion km away.', source:'NASA JPL', publishedAt:new Date('2025-03-19'), imageUrl:'https://picsum.photos/seed/sci10/800/450', url:'https://jpl.nasa.gov/voyager1-2025', category:Category.science, regionCode:'US', locale:'en' },
  { strapiId:'sci-11', title:'Quantum Internet Node Established Between Two Cities', description:'Researchers establish the first quantum internet node between Amsterdam and Delft, transmitting entangled photons over 50km.', source:'Nature', publishedAt:new Date('2025-03-21'), imageUrl:'https://picsum.photos/seed/sci11/800/450', url:'https://nature.com/quantum-internet-node', category:Category.science, regionCode:'NL', locale:'en' },
  { strapiId:'sci-12', title:'Antarctic Ice Sheet Loss Accelerates to Record Rate', description:'New satellite data shows the Antarctic ice sheet is losing mass at a record rate of 300 billion tonnes per year.', source:'Science Advances', publishedAt:new Date('2025-03-23'), imageUrl:'https://picsum.photos/seed/sci12/800/450', url:'https://advances.sciencemag.org/antarctic-ice-2025', category:Category.science, regionCode:null, locale:'en' },
  { strapiId:'sci-13', title:'Synthetic Biology Creates First Fully Artificial Cell', description:'Scientists at the J. Craig Venter Institute create the first fully artificial cell with a synthetic genome and membrane.', source:'Cell', publishedAt:new Date('2025-03-25'), imageUrl:'https://picsum.photos/seed/sci13/800/450', url:'https://cell.com/synthetic-cell-2025', category:Category.science, regionCode:'US', locale:'en' },
  { strapiId:'sci-14', title:'Dark Matter Detector Finds No Signal After 10 Years', description:'The LUX-ZEPLIN dark matter detector completes its 10-year run with no signal, ruling out large classes of WIMP candidates.', source:'Physical Review D', publishedAt:new Date('2025-03-27'), imageUrl:'https://picsum.photos/seed/sci14/800/450', url:'https://journals.aps.org/lz-results', category:Category.science, regionCode:null, locale:'en' },
  { strapiId:'sci-15', title:'Coral Reef Restoration Using 3D-Printed Structures Succeeds', description:'A large-scale trial of 3D-printed ceramic reef structures in the Great Barrier Reef shows 80% coral colonisation after two years.', source:'Nature Sustainability', publishedAt:new Date('2025-03-29'), imageUrl:'https://picsum.photos/seed/sci15/800/450', url:'https://nature.com/coral-3d-print', category:Category.science, regionCode:'AU', locale:'en' },
  { strapiId:'sci-16', title:'Exoplanet with Liquid Water Ocean Confirmed', description:'Astronomers confirm the presence of a liquid water ocean on exoplanet K2-18b using JWST spectroscopy data.', source:'Astrophysical Journal Letters', publishedAt:new Date('2025-03-31'), imageUrl:'https://picsum.photos/seed/sci16/800/450', url:'https://iopscience.iop.org/k2-18b-ocean', category:Category.science, regionCode:null, locale:'en' },
  { strapiId:'sci-17', title:'Brain-Computer Interface Restores Speech in Paralysed Patient', description:'A BCI implant enables a paralysed patient to speak at 78 words per minute by decoding neural signals in real time.', source:'Nature Neuroscience', publishedAt:new Date('2025-04-02'), imageUrl:'https://picsum.photos/seed/sci17/800/450', url:'https://nature.com/bci-speech-2025', category:Category.science, regionCode:'US', locale:'en' },
  { strapiId:'sci-18', title:'New Antibiotic Kills Drug-Resistant Bacteria in Animal Trials', description:'A novel antibiotic compound derived from soil bacteria kills MRSA and other drug-resistant pathogens in animal trials.', source:'Nature Chemical Biology', publishedAt:new Date('2025-04-04'), imageUrl:'https://picsum.photos/seed/sci18/800/450', url:'https://nature.com/new-antibiotic-2025', category:Category.science, regionCode:null, locale:'en' },
  { strapiId:'sci-19', title:'Hydrogen-Powered Aircraft Completes Transatlantic Flight', description:'A hydrogen fuel cell aircraft completes the first transatlantic flight, covering 5,500km with zero carbon emissions.', source:'Aviation Week', publishedAt:new Date('2025-04-06'), imageUrl:'https://picsum.photos/seed/sci19/800/450', url:'https://aviationweek.com/hydrogen-transatlantic', category:Category.science, regionCode:null, locale:'en' },
  { strapiId:'sci-20', title:'Scientists Photograph Black Hole Jet for First Time', description:'The Event Horizon Telescope captures the first detailed image of a relativistic jet emerging from a supermassive black hole.', source:'Astronomy & Astrophysics', publishedAt:new Date('2025-04-08'), imageUrl:'https://picsum.photos/seed/sci20/800/450', url:'https://aanda.org/black-hole-jet-2025', category:Category.science, regionCode:null, locale:'en' },
];

async function main() {
  console.log('🌱 Seeding database...');
  let created = 0;
  for (const item of items) {
    await prisma.trendItem.upsert({
      where: { strapiId: item.strapiId },
      create: item,
      update: item,
    });
    created++;
  }
  console.log(`✅ Seeded ${created} trend items (${created / 20} categories × 20 records)`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
